// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scewhpkvjoktzpxggbgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjZXdocGt2am9rdHpweGdnYmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjM1MjUsImV4cCI6MjA2NjczOTUyNX0.VsR7KTiKlbw7YImUVW4ylTbzdHxksKvlkJMVS8RR3tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);